/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpContext,
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { AdminPatchPaymentRequestDto } from '../model/adminPatchPaymentRequestDto';
// @ts-ignore
import { AdminPaymentHistoryEntryResponseDto } from '../model/adminPaymentHistoryEntryResponseDto';
// @ts-ignore
import { AdminPaymentRowResponseDto } from '../model/adminPaymentRowResponseDto';
// @ts-ignore
import { PagedResponseAdminPaymentRowResponseDto } from '../model/pagedResponseAdminPaymentRowResponseDto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
  providedIn: 'root',
})
export class AdminPaymentsService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration
  ) {
    super(basePath, configuration);
  }

  /**
   * @endpoint get /api/admin/payments/{reservationId}/history
   * @param reservationId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public history(
    reservationId: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<Array<AdminPaymentHistoryEntryResponseDto>>;
  public history(
    reservationId: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<Array<AdminPaymentHistoryEntryResponseDto>>>;
  public history(
    reservationId: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<Array<AdminPaymentHistoryEntryResponseDto>>>;
  public history(
    reservationId: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    if (reservationId === null || reservationId === undefined) {
      throw new Error(
        'Required parameter reservationId was null or undefined when calling history.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer '
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['*/*']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/admin/payments/${this.configuration.encodeParam({ name: 'reservationId', value: reservationId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/history`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Array<AdminPaymentHistoryEntryResponseDto>>(
      'get',
      `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * @endpoint get /api/admin/payments
   * @param status
   * @param dateFrom
   * @param dateTo
   * @param page
   * @param size
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public list3(
    status?: 'DEPOSIT_PENDING' | 'DEPOSIT_PAID' | 'EXEMPT' | 'WAIVED' | 'REFUNDED',
    dateFrom?: string,
    dateTo?: string,
    page?: number,
    size?: number,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<PagedResponseAdminPaymentRowResponseDto>;
  public list3(
    status?: 'DEPOSIT_PENDING' | 'DEPOSIT_PAID' | 'EXEMPT' | 'WAIVED' | 'REFUNDED',
    dateFrom?: string,
    dateTo?: string,
    page?: number,
    size?: number,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<PagedResponseAdminPaymentRowResponseDto>>;
  public list3(
    status?: 'DEPOSIT_PENDING' | 'DEPOSIT_PAID' | 'EXEMPT' | 'WAIVED' | 'REFUNDED',
    dateFrom?: string,
    dateTo?: string,
    page?: number,
    size?: number,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<PagedResponseAdminPaymentRowResponseDto>>;
  public list3(
    status?: 'DEPOSIT_PENDING' | 'DEPOSIT_PAID' | 'EXEMPT' | 'WAIVED' | 'REFUNDED',
    dateFrom?: string,
    dateTo?: string,
    page?: number,
    size?: number,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'status',
      <any>status,
      QueryParamStyle.Form,
      true
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'dateFrom',
      <any>dateFrom,
      QueryParamStyle.Form,
      true
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'dateTo',
      <any>dateTo,
      QueryParamStyle.Form,
      true
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'page',
      <any>page,
      QueryParamStyle.Form,
      true
    );

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'size',
      <any>size,
      QueryParamStyle.Form,
      true
    );

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer '
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['*/*']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/admin/payments`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PagedResponseAdminPaymentRowResponseDto>(
      'get',
      `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * @endpoint patch /api/admin/payments/{reservationId}
   * @param reservationId
   * @param adminPatchPaymentRequestDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public patch(
    reservationId: string,
    adminPatchPaymentRequestDto: AdminPatchPaymentRequestDto,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<AdminPaymentRowResponseDto>;
  public patch(
    reservationId: string,
    adminPatchPaymentRequestDto: AdminPatchPaymentRequestDto,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpResponse<AdminPaymentRowResponseDto>>;
  public patch(
    reservationId: string,
    adminPatchPaymentRequestDto: AdminPatchPaymentRequestDto,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<HttpEvent<AdminPaymentRowResponseDto>>;
  public patch(
    reservationId: string,
    adminPatchPaymentRequestDto: AdminPatchPaymentRequestDto,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext; transferCache?: boolean }
  ): Observable<any> {
    if (reservationId === null || reservationId === undefined) {
      throw new Error('Required parameter reservationId was null or undefined when calling patch.');
    }
    if (adminPatchPaymentRequestDto === null || adminPatchPaymentRequestDto === undefined) {
      throw new Error(
        'Required parameter adminPatchPaymentRequestDto was null or undefined when calling patch.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (bearerAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer '
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['*/*']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/admin/payments/${this.configuration.encodeParam({ name: 'reservationId', value: reservationId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<AdminPaymentRowResponseDto>(
      'patch',
      `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: adminPatchPaymentRequestDto,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress,
      }
    );
  }
}
