export * from './adminAudit.service';
import { AdminAuditService } from './adminAudit.service';
export * from './adminBlackouts.service';
import { AdminBlackoutsService } from './adminBlackouts.service';
export * from './adminExports.service';
import { AdminExportsService } from './adminExports.service';
export * from './adminGroups.service';
import { AdminGroupsService } from './adminGroups.service';
export * from './adminPayments.service';
import { AdminPaymentsService } from './adminPayments.service';
export * from './adminReservations.service';
import { AdminReservationsService } from './adminReservations.service';
export * from './adminStats.service';
import { AdminStatsService } from './adminStats.service';
export * from './adminUsers.service';
import { AdminUsersService } from './adminUsers.service';
export * from './agoraAuth.service';
import { AgoraAuthService } from './agoraAuth.service';
export * from './calendar.service';
import { CalendarService } from './calendar.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './reservationDocuments.service';
import { ReservationDocumentsService } from './reservationDocuments.service';
export * from './reservations.service';
import { ReservationsService } from './reservations.service';
export * from './resources.service';
import { ResourcesService } from './resources.service';
export * from './superadmin.service';
import { SuperadminService } from './superadmin.service';
export * from './waitlist.service';
import { WaitlistService } from './waitlist.service';
export const APIS = [AdminAuditService, AdminBlackoutsService, AdminExportsService, AdminGroupsService, AdminPaymentsService, AdminReservationsService, AdminStatsService, AdminUsersService, AgoraAuthService, CalendarService, GroupsService, ReservationDocumentsService, ReservationsService, ResourcesService, SuperadminService, WaitlistService];
