/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminAuditEntryResponse } from './adminAuditEntryResponse';

export interface AdminAuditPageResponse {
  content?: Array<AdminAuditEntryResponse>;
  totalElements?: number;
  totalPages?: number;
}
