/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminAuditEntryResponse { 
    id?: string;
    adminName?: string;
    targetName?: string;
    action?: string;
    details?: { [key: string]: object; };
    isImpersonation?: boolean;
    performedAt?: string;
}

