/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AdminPaymentRowResponseDto {
  reservationId?: string;
  status?: AdminPaymentRowResponseDto.StatusEnum;
  amountCents?: number;
  paymentMode?: AdminPaymentRowResponseDto.PaymentModeEnum;
  checkNumber?: string;
  comment?: string;
  updatedByName?: string;
  updatedAt?: string;
}
export namespace AdminPaymentRowResponseDto {
  export const StatusEnum = {
    DepositPending: 'DEPOSIT_PENDING',
    DepositPaid: 'DEPOSIT_PAID',
    Exempt: 'EXEMPT',
    Waived: 'WAIVED',
    Refunded: 'REFUNDED',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
  export const PaymentModeEnum = {
    Cash: 'CASH',
    Check: 'CHECK',
  } as const;
  export type PaymentModeEnum = (typeof PaymentModeEnum)[keyof typeof PaymentModeEnum];
}
