/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminDashboardStatsResponseDto { 
    todayReservations?: number;
    pendingDeposits?: number;
    pendingDocuments?: number;
    tutoredAccounts?: number;
    totalGroups?: number;
}

