/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminSupportUserDto { 
    id?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    status?: AdminSupportUserDto.StatusEnum;
}
export namespace AdminSupportUserDto {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Deleted: 'DELETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


