/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminReservationListStatsResponseDto { 
    total?: number;
    pendingGroup?: number;
    confirmed?: number;
    cancelled?: number;
    rejected?: number;
    depositPending?: number;
    exemptOrWaived?: number;
}

