/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminUserGroupSnippetDto } from './adminUserGroupSnippetDto';

export interface AdminUserDetailResponseDto {
  id?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  accountType?: string;
  status?: string;
  phone?: string;
  internalRef?: string;
  notesAdmin?: string;
  groups?: Array<AdminUserGroupSnippetDto>;
  createdAt?: string;
}
