/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserGroupSummaryDto } from './userGroupSummaryDto';

export interface AuthMeResponseDto {
  id?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  accountType?: AuthMeResponseDto.AccountTypeEnum;
  status?: AuthMeResponseDto.StatusEnum;
  phone?: string;
  groups?: Array<UserGroupSummaryDto>;
  createdAt?: string;
}
export namespace AuthMeResponseDto {
  export const AccountTypeEnum = {
    Autonomous: 'AUTONOMOUS',
    Tutored: 'TUTORED',
  } as const;
  export type AccountTypeEnum = (typeof AccountTypeEnum)[keyof typeof AccountTypeEnum];
  export const StatusEnum = {
    Active: 'ACTIVE',
    Deleted: 'DELETED',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
