/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserGroupSummaryDto } from './userGroupSummaryDto';

export interface AuthMeResponseDto {
  id?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  accountType?: AuthMeResponseDto.AccountTypeEnum;
  status?: AuthMeResponseDto.StatusEnum;
  phone?: string;
  roles?: Array<AuthMeResponseDto.RolesEnum>;
  groups?: Array<UserGroupSummaryDto>;
  createdAt?: string;
  /**
   * Promotion métier ADMIN_SUPPORT (compte habilité au périmètre support), distinct du rôle JWT SECRETARY_ADMIN.
   */
  adminSupport?: boolean;
}
export namespace AuthMeResponseDto {
  export const AccountTypeEnum = {
    Autonomous: 'AUTONOMOUS',
    Tutored: 'TUTORED',
  } as const;
  export type AccountTypeEnum = (typeof AccountTypeEnum)[keyof typeof AccountTypeEnum];
  export const StatusEnum = {
    Active: 'ACTIVE',
    Deleted: 'DELETED',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
  export const RolesEnum = {
    Citizen: 'CITIZEN',
    Superadmin: 'SUPERADMIN',
    SecretaryAdmin: 'SECRETARY_ADMIN',
    DelegateAdmin: 'DELEGATE_ADMIN',
    GroupManager: 'GROUP_MANAGER',
  } as const;
  export type RolesEnum = (typeof RolesEnum)[keyof typeof RolesEnum];
}
