/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlackoutPeriodResponseDto { 
    id?: string;
    resourceId?: string;
    resourceName?: string;
    dateFrom?: string;
    dateTo?: string;
    reason?: string;
    createdByName?: string;
}

