/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarDayDto } from './calendarDayDto';


/**
 * Vue calendrier mensuelle (créneaux par ressource, alignée sur le contrat API AGORA)
 */
export interface CalendarResponseDto { 
    /**
     * Année
     */
    year?: number;
    /**
     * Mois (1-12)
     */
    month?: number;
    /**
     * Un élément par jour du mois, trié par date
     */
    days?: Array<CalendarDayDto>;
}

