/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarSlotDto } from './calendarSlotDto';

/**
 * Jour calendrier avec créneaux et éventuelle fermeture
 */
export interface CalendarDayDto {
  /**
   * Date (ISO)
   */
  date?: string;
  /**
   * Jour entièrement fermé (blackout)
   */
  isBlackout?: boolean;
  /**
   * Motif de fermeture si blackout
   */
  blackoutReason?: string | null;
  /**
   * Créneaux par ressource, triés par nom de ressource puis heure de début
   */
  slots?: Array<CalendarSlotDto>;
}
