/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Créneau horaire pour une ressource donnée
 */
export interface CalendarSlotDto {
  /**
   * Identifiant de la ressource
   */
  resourceId?: string;
  /**
   * Nom affiché de la ressource
   */
  resourceName?: string;
  /**
   * IMMOBILIER ou MOBILIER
   */
  resourceType?: CalendarSlotDto.ResourceTypeEnum;
  /**
   * Heure de début (HH:mm)
   */
  slotStart?: string;
  /**
   * Heure de fin (HH:mm)
   */
  slotEnd?: string;
  /**
   * false si une réservation bloquante occupe le créneau
   */
  isAvailable?: boolean;
}
export namespace CalendarSlotDto {
  export const ResourceTypeEnum = {
    Immobilier: 'IMMOBILIER',
    Mobilier: 'MOBILIER',
  } as const;
  export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];
}
