/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';


export interface CreateRecurringReservationRequestDto { 
    resourceId: string;
    slotStart: LocalTime;
    slotEnd: LocalTime;
    purpose: string;
    groupId?: string;
    frequency: CreateRecurringReservationRequestDto.FrequencyEnum;
    startDate: string;
    endDate: string;
    excludedDates?: Array<string>;
}
export namespace CreateRecurringReservationRequestDto {
    export const FrequencyEnum = {
        Weekly: 'WEEKLY',
        Biweekly: 'BIWEEKLY',
        Monthly: 'MONTHLY'
    } as const;
    export type FrequencyEnum = typeof FrequencyEnum[keyof typeof FrequencyEnum];
}


