/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';

export interface CreateReservationRequestDto {
  resourceId: string;
  date: string;
  slotStart: LocalTime;
  slotEnd: LocalTime;
  purpose: string;
  groupId?: string;
}
