/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Jeton d\'accès court pour session d\'impersonation (comptes TUTORED)
 */
export interface ImpersonationTokenResponseDto {
  /**
   * JWT access ; le sub est l\'UUID du compte cible
   */
  accessToken?: string;
  /**
   * Durée de vie du jeton en secondes
   */
  expiresInSeconds?: number;
}
