/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPaymentRowResponseDto } from './adminPaymentRowResponseDto';


export interface PagedResponseAdminPaymentRowResponseDto { 
    content?: Array<AdminPaymentRowResponseDto>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

