/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceDto } from './resourceDto';

export interface PagedResponseResourceDto {
  content?: Array<ResourceDto>;
  totalElements?: number;
  totalPages?: number;
  page?: number;
  size?: number;
}
