/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ReservationDocumentResponseDto {
  id?: string;
  docType?: ReservationDocumentResponseDto.DocTypeEnum;
  originalFilename?: string;
  mimeType?: string;
  sizeBytes?: number;
  status?: ReservationDocumentResponseDto.StatusEnum;
  sentAt?: string;
}
export namespace ReservationDocumentResponseDto {
  export const DocTypeEnum = {
    AssociationProof: 'ASSOCIATION_PROOF',
    Identity: 'IDENTITY',
    SocialProof: 'SOCIAL_PROOF',
    MandateProof: 'MANDATE_PROOF',
    WordExcelDoc: 'WORD_EXCEL_DOC',
    Other: 'OTHER',
  } as const;
  export type DocTypeEnum = (typeof DocTypeEnum)[keyof typeof DocTypeEnum];
  export const StatusEnum = {
    Sent: 'SENT',
    Failed: 'FAILED',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
