/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReservationResourceDto { 
    id?: string;
    name?: string;
    resourceType?: ReservationResourceDto.ResourceTypeEnum;
    capacity?: number;
    depositAmountCents?: number;
    imageUrl?: string;
}
export namespace ReservationResourceDto {
    export const ResourceTypeEnum = {
        Immobilier: 'IMMOBILIER',
        Mobilier: 'MOBILIER'
    } as const;
    export type ResourceTypeEnum = typeof ResourceTypeEnum[keyof typeof ResourceTypeEnum];
}


