/**
 * AGORA API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ResourceRequest {
  name: string;
  resourceType: ResourceRequest.ResourceTypeEnum;
  capacity?: number;
  description?: string;
  depositAmountCents?: number;
  rentalPriceCents?: number;
  imageUrl?: string;
  accessibilityTags: Array<string>;
}
export namespace ResourceRequest {
  export const ResourceTypeEnum = {
    Immobilier: 'IMMOBILIER',
    Mobilier: 'MOBILIER',
  } as const;
  export type ResourceTypeEnum = (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];
}
