/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceDto { 
    id?: string;
    name?: string;
    resourceType?: ResourceDto.ResourceTypeEnum;
    capacity?: number;
    description?: string;
    depositAmountCents?: number;
    /** Tarif de location en centimes ; absent ou null si non renseigne cote catalogue. */
    rentalPriceCents?: number;
    imageUrl?: string;
    accessibilityTags?: Array<string>;
    isActive?: boolean;
}
export namespace ResourceDto {
    export const ResourceTypeEnum = {
        Immobilier: 'IMMOBILIER',
        Mobilier: 'MOBILIER'
    } as const;
    export type ResourceTypeEnum = typeof ResourceTypeEnum[keyof typeof ResourceTypeEnum];
}


