/**
 * AGORA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WaitlistEntryResponseDto { 
    id?: string;
    resourceName?: string;
    slotDate?: string;
    slotStart?: string;
    slotEnd?: string;
    position?: number;
    status?: string;
    notifiedAt?: string;
}

